'use client'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'
import './globals.css'
import style from '@/styles/common.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
